# Generated by Django 3.0.7 on 2020-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=500)),
                ('lawyerid', models.CharField(max_length=500)),
                ('appointmentdate', models.CharField(default='', max_length=500)),
                ('appointmenttime', models.CharField(default='', max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('lasthearingdate', models.CharField(default='', max_length=500)),
                ('nexthearingdate', models.CharField(default='', max_length=500)),
                ('casestatus', models.CharField(default='', max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('clientid', models.CharField(max_length=500)),
                ('lawyerid', models.CharField(max_length=500)),
                ('lawyeracceptance', models.CharField(default='', max_length=500)),
                ('postedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('caseid', models.CharField(max_length=500)),
                ('uploaddate', models.CharField(max_length=500)),
                ('documentname', models.FileField(upload_to='documents')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='LawyerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'lawyers',
            },
        ),
    ]
